add sshpass functionality

diff --git a/ucs-domjoin b/ucs-domjoin
--- a/ucs-domjoin
+++ b/ucs-domjoin
@@ -1,8 +1,8 @@
-#!/bin/sh
+#!/bin/bash
 # ucs-domjoin
 #  Make Linux systems part of a UCS domain (inspired by http://wiki.univention.de/index.php?title=Ubuntu)
 #
-# Depends: dig, wget, sssd, lsb_release, ssh, ldap-utils, ntpdate, krb5, (Debian-based systems: pam-auth-update, auth-client-config)
+# Depends: dig, wget, sssd, lsb_release, ssh, ldap-utils, ntpdate, krb5, sshpass (Debian-based systems: pam-auth-update, auth-client-config)
 #
 # Copyright (C) 2012,2013 Jan Christoph Ebersbach
 #
@@ -35,26 +35,38 @@ set -u
 set -e
 
 query () { # Currently not in use {{{1
-	local text allowempty result
+	local text default allowempty result
 	text="$1"           # text displayed to the user, e.g. a question/decision
-	default="$2"        # default result in case the user didn't type anything
-	forcenonempty="$3"  # if empty the user is queried again
+	default=
+	if [[ $# -ge 2 ]]; then
+		default="$2"        # default result in case the user didn't type anything
+	fi
+	allowempty=
+	if [[ $# -ge 3 ]]; then
+		allowempty="$3"     # if non-empty the user isn't queried again
+	fi
 
 	while true; do
-		echo -n "${text} "
-		# read result
+		echo -n "${text} " 1>&2
+		read result
 		if [[ -n "${default}" ]] && [[ -z "${result}" ]]; then
 			result="${default}"
 		fi
-		if [[ -n "${forcenonempty}" ]] && [[ -z "${result}" ]]; then
+		if [[ -z "${allowempty}" ]] && [[ -z "${result}" ]]; then
 			echo "Please specify a non-empty value." 1>&2
 			continue
 		fi
-		echo "$result"
+		echo -n "$result"
 		break
 	done
 	return 0
 } # }}}1
+
+query_password () {
+	stty -echo
+	query "$@"
+	stty echo
+}
 
 log () { # {{{1
 	echo -e "INFO: $@"
@@ -78,13 +90,13 @@ findmaster () { # {{{1
 	set +e
 	master=$(dig -t SRV _domaincontroller_master._tcp +short +search | awk '{print $4}')
 	set -e
-	if [ $? -ne 0 ]; then
+	if [ $? -ne 0 ] || [[ -z "${master}" ]]; then
 		error "ERROR: Unable to find UCS Master"
 	fi
 	echo "${master}"
 } # }}}1
 
-log "Testing dependencies" # {{{1
+log "Testing dependencies." # {{{1
 testcmd ldapsearch
 testcmd sssd
 testcmd dig
@@ -93,6 +105,7 @@ testcmd ssh
 testcmd ntpdate
 testcmd kinit
 testcmd lsb_release
+testcmd sshpass
 if lsb_release -is | grep -q 'buntu' ; then
 	testcmd auth-client-config
 	testcmd pam-auth-update
@@ -110,33 +123,51 @@ if [ "$(whoami)" != 'root' ]; then
 	error "root privileges are required to perform a domain join.  Use sudo or su to execute this script."
 fi
 
-log "Looking for UCS Master (DNS service record _domaincontroller_master._tcp)"
+if [ -e /var/univention-join/joined ]; then
+	case "$(query 'System is already joined!  Join again? [yN]' 'N')" in
+		y|Y)
+			log 'Starting rejoin.'
+			;;
+		*)
+			error 'Abort join.'
+			;;
+	esac
+fi
+
+log "Looking for UCS Master (DNS service record _domaincontroller_master._tcp)."
 MASTER="$(findmaster)"
 MASTER_IP="$(dig -t A "${MASTER}" +short)"
-log "Found UCS Master: $MASTER ($MASTER_IP)"
+log "Found UCS Master: $MASTER ($MASTER_IP)."
 
+ROOT_PASSWORD="$(mktemp)"
+trap "rm -f '$ROOT_PASSWORD'" 0               # EXIT
+trap "rm -f '$ROOT_PASSWORD'; exit 1" 2       # INT
+trap "rm -f '$ROOT_PASSWORD'; exit 1" 1 15    # HUP TERM
+query_password "Please enter root password for system ${MASTER}:" > "${ROOT_PASSWORD}"
+sshpass -f "${ROOT_PASSWORD}" ssh "root@${MASTER}" log "SSH access is working." || error "SSH access failed."
 # }}}1
 
-log "Preparing configuration at /etc/univention" # {{{1
+log "Preparing configuration." # {{{1
 mkdir -p /etc/univention
+mkdir -p /var/univention-join
 
-log "Retrieving UCR configuration from root@${MASTER}" # {{{2
-ssh root@${MASTER} ucr shell | grep -v ^hostname= >/etc/univention/ucr_master
+log "Retrieving UCR configuration from root@${MASTER}." # {{{2
+sshpass -f "${ROOT_PASSWORD}" ssh "root@${MASTER}" ucr shell | grep -v ^hostname= >/etc/univention/ucr_master
 . /etc/univention/ucr_master
 # }}}2
 
-log "Adding ${ldap_master} to /etc/hosts" # {{{2
-grep -q "${ldap_master}" /etc/hosts || echo "${MASTER_IP} ${ldap_master}" >> /etc/hosts
+log "Adding ${ldap_master} to /etc/hosts." # {{{2
+grep -q "${ldap_master}" /etc/hosts || echo "$(dig "${ldap_master}" +short) ${ldap_master}" >> /etc/hosts
 # }}}2
 
-log "Retrieving SSL CA, storing it at /etc/univention/ssl/ucsCA/CAcert.pem" {{{2
+log "Retrieving SSL CA, storing it at /etc/univention/ssl/ucsCA/CAcert.pem." {{{2
 mkdir -p /etc/univention/ssl/ucsCA/
 wget --quiet --no-check-certificate -O /etc/univention/ssl/ucsCA/CAcert.pem http://${ldap_master}/ucs-root-ca.crt
 chmod a+r /etc/univention/ssl/ucsCA/CAcert.pem
 # }}}2
 # }}}1
 
-log "Creating account for this computer" # {{{1
+log "Creating account for this computer." # {{{1
 password="$(< /dev/urandom tr -dc A-Za-z0-9_ | head -c20)"
 ldap_position="cn=computers,${ldap_base}"
 hostname="$(hostname)"
@@ -148,11 +179,26 @@ for interface in /sys/class/net/*; do
 	mac_addresses="${mac_addresses} --set mac=$(cat ${interface}/address)"
 done
 
+
+existing_host_dn=$(sshpass -f "${ROOT_PASSWORD}" ssh "root@${ldap_master}" udm computers/computer list --filter name="${hostname}" | sed -ne 's/^DN: //p' || true)
+if [[ -n "${existing_host_dn}" ]]; then
+	case "$(query 'Host exists with DN: ${existing_host_dn}.  Delete it? [yN]' 'N')" in
+		y|Y)
+			log 'Deleting host.'
+			existing_host_type=$(sshpass -f "${ROOT_PASSWORD}" ssh "root@${ldap_master}" univention-ldapsearch -s base -LLL -b "${existing_host_dn}" univentionObjectType | sed -ne 's/^univentionObjectType: //p')
+			sshpass -f "${ROOT_PASSWORD}" ssh "root@${ldap_master}" udm "${existing_host_type}" remove --dn "${existing_host_dn}"
+			;;
+		*)
+			error 'Abort join.'
+			;;
+	esac
+fi
+
 # TODO add IP addresses and register a DNS entry for this client as well
 #ip_addresses=
 if [ "$version_version" = 3.0 ] && [ "$version_patchlevel" -lt 2 ]; then
 	type="computers/managedclient"
-	ssh root@${ldap_master} udm "${type}" create --position "${ldap_position}" \
+	sshpass -f "${ROOT_PASSWORD}" ssh "root@${ldap_master}" udm "${type}" create --position "${ldap_position}" \
 		--set name="${hostname}" --set password="${password}" $mac_addresses \
 		--set description="$(lsb_release -d)"
 else
@@ -161,7 +207,7 @@ else
 	else
 		type="computers/linux"
 	fi
-	ssh root@${ldap_master} udm "${type}" create --position "${ldap_position}" \
+	sshpass -f "${ROOT_PASSWORD}" ssh "root@${ldap_master}" udm "${type}" create --position "${ldap_position}" \
 		--set name="${hostname}" --set password="${password}" \
 		--set description="$(lsb_release -d)" \
 		--set operatingSystem="$(lsb_release -is)" \
@@ -172,9 +218,11 @@ chmod 640 /etc/ldap.secret
 echo "${password}" > /etc/ldap.secret
 # }}}1
 
-log "Creating LDAP configuration" # {{{1
-# openldap_dir=/etc/ldap # TODO autodetect configuration directory
-openldap_dir=/etc/openldap
+log "Creating LDAP configuration." # {{{1
+openldap_dir=/etc/ldap # TODO improve autodetectin of configuration directory
+if [[ ! -e "${openldap_dir}" ]]; then
+	openldap_dir=/etc/openldap
+fi
 mkdir -p "${openldap_dir}"
 
 # Create ldap.conf
@@ -186,7 +234,7 @@ BASE $ldap_base
 __EOF__
 # }}}1
 
-# log "Creating nss_ldap configuration" # {{{1
+# log "Creating nss_ldap configuration." # {{{1
 #cat >/etc/ldap.conf <<__EOF__
 #uri ldap://$ldap_master:7389
 #rootbinddn ${dn}
@@ -203,7 +251,7 @@ __EOF__
 #auth-client-config -t nss -p lac_ldap
 # }}}1
 
-log "Creating sssd configuration" # {{{1
+log "Creating sssd configuration." # {{{1
 mkdir -p /etc/sssd
 touch /etc/sssd/sssd.conf
 chmod 600 /etc/sssd/sssd.conf
@@ -240,9 +288,9 @@ ldap_default_authtok = $(cat /etc/ldap.secret)
 __EOF__
 # }}}1
 
-log "Configuring nsswitch.conf and pam" {{{1
+log "Configuring nsswitch.conf and pam." {{{1
 if [ -d /etc/auth-client-config/profile.d ]; then
-	log "Creating sss auth-client-config profile" # {{{2
+	log "Creating sss auth-client-config profile." # {{{2
 	cat > /etc/auth-client-config/profile.d/sss <<__EOF__
 [sss]
 nss_passwd=     passwd:         compat sss
@@ -276,7 +324,7 @@ __EOF__
 	service sssd start
 	# }}}2
 
-	log "Creating mkhomedir configuration" # {{{2
+	log "Creating mkhomedir configuration." # {{{2
 	cat >/usr/share/pam-configs/ucs_mkhomedir <<__EOF__
 Name: activate mkhomedir
 Default: yes
@@ -289,7 +337,7 @@ __EOF__
 	DEBIAN_FRONTEND=noninteractive pam-auth-update
 	# }}}2
 
-	log "Creating security group configuration" # {{{2
+	log "Creating security group configuration." # {{{2
 	echo '*;*;*;Al0000-2400;audio,cdrom,dialout,floppy,plugdev,adm,games' >>/etc/security/group.conf
 
 	cat >>/usr/share/pam-configs/local_groups <<__EOF__
@@ -307,7 +355,7 @@ else
 fi
 # }}}1
 
-log "Configuring lightdm greater" # {{{1
+log "Configuring lightdm greater." # {{{1
 if [ -e /etc/lightdm/lightdm.conf ]; then
 	# Add a field for a user name
 	grep -q "greeter-show-manual-login=true" /etc/lightdm/lightdm.conf || echo "greeter-show-manual-login=true" >> /etc/lightdm/lightdm.conf
@@ -316,7 +364,7 @@ if [ -e /etc/lightdm/lightdm.conf ]; then
 	grep -q "greeter-hide-users=true" /etc/lightdm/lightdm.conf || echo "greeter-hide-users=true" >> /etc/lightdm/lightdm.conf
 fi # }}}1
 
-log "Creating kerberos configuration" # {{{1
+log "Creating kerberos configuration." # {{{1
 cat >/etc/krb5.conf <<__EOF__
 [libdefaults]
     default_realm = $kerberos_realm
@@ -333,7 +381,7 @@ $kerberos_realm = {
 __EOF__
 # }}}1
 
-log "Disabling avahi-daemon" # {{{1
+log "Disabling avahi-daemon because it inters with SSSD service." # {{{1
 if type service; then
 	service avahi-daemon stop
 	sed -i 's|start on (|start on (never and |' /etc/init/avahi-daemon.conf
@@ -342,8 +390,12 @@ else
 fi
 # }}}1
 
-log "Synchronize time with the UCS master" # {{{1
+log "Synchronizing time with UCS master." # {{{1
 ntpdate $ldap_master
+# }}}1
+
+log "Finished join." # {{{1
+touch /var/univention-join/joined
 # }}}1
 
 # TODO es können sowohl ccreds als auch sssd verwendet werden, in beiden fällen müssen pakete aus aur installiert werden
